#pragma once

float DELTA_T;

#define BOARD_DIM 20
#define BOARD_ROWS BOARD_DIM
#define BOARD_COLS BOARD_DIM * 2

#define BULLET_SPEED 1
#define RELOAD_SPEED 1
#define ENEMY_RELOAD_SPEED 5

#define BULLET_DAMABE 1
#define ENEMY_BULLET_DAMAGE 1

#define BACKGROUND_COLOR COLOR_BLACK 
#define PLAYER_COLOR COLOR_WHITE
#define ENEMY_COLOR COLOR_WHITE

#define BULLET_COLOR COLOR_YELLOW
#define EMEMY_BULLET_COLOR COLOR_RED