#pragma once

#include <ncurses.h>

float DELTA_T;

#define BOARD_DIM 20
#define BOARD_ROWS BOARD_DIM
#define BOARD_COLS BOARD_DIM * 2

#define BULLET_SPEED 2
#define ENEMY_BULLET_SPEED 2
#define RELOAD_SPEED 3
#define ENEMY_RELOAD_SPEED 5

#define BULLET_DAMABE 1
#define ENEMY_BULLET_DAMAGE 1

#define BACKGROUND_COLOR -1
#define BORDER_COLOR COLOR_WHITE

#define PLAYER_COLOR COLOR_CYAN
#define ENEMY_COLOR COLOR_RED

#define BULLET_COLOR COLOR_YELLOW
#define ENEMY_BULLET_COLOR COLOR_RED

enum PairColors
{
    PLAYER_PAIR_COLOR,
    ENEMY_PAIR_COLOR,
    BULLET_PAIR_COLOR,
    ENEMY_BULLET_PAIR_COLOR
};
void initGameColorPairs()
{
    init_pair(PLAYER_PAIR_COLOR, PLAYER_COLOR, BACKGROUND_COLOR);
    init_pair(ENEMY_PAIR_COLOR, ENEMY_COLOR, BACKGROUND_COLOR);
    init_pair(BULLET_PAIR_COLOR, BULLET_COLOR, BACKGROUND_COLOR);
    init_pair(ENEMY_BULLET_PAIR_COLOR, ENEMY_BULLET_COLOR, BACKGROUND_COLOR);
}
    